# config.toml

[server]
# url = "http://127.0.0.1:18181/"
url = "http://192.168.88.247:80/"

[hardware]
# disable_ports = ["capture_1"] #, "capture_2"]
# All-to-all routing: connect all hardware inputs to all first plugin inputs
# join_audio_inputs = true
# All-to-all routing: connect all last plugin outputs to all hardware outputs
# join_audio_outputs = true

[rack]
routing_mode = "hard_bypass"  # one of [hard_bypass, linear, dual_track], default=hard_bypass
allow_all_plugins = true

# =============================================================================
# Plugins
# =============================================================================

# --- Distortion / Overdrive (original) ---

[[plugins]]
name = "GxTubeScreamer"
uri = "http://guitarix.sourceforge.net/plugins/gxts9#ts9sim"
category = "distortion"

# --- Reverb (original) ---

# [[plugins]]
# name = "Calf Reverb"
# uri = "http://calf.sourceforge.net/plugins/Reverb"
# category = "reverb"

# [[plugins]]
# name = "Dragonfly Hall Reverb"
# uri = "https://github.com/michaelwillis/dragonfly-reverb"
# category = "reverb"

# --- Delay (original) ---

# [[plugins]]
# name = "MDA Delay"
# uri = "http://moddevices.com/plugins/mda/Delay"
# category = "delay"

# =============================================================================
# Plugins (from server)
# =============================================================================

# --- Simulators / Amps ---

[[plugins]]
name = "Neural Amp Modeler"
uri = "http://github.com/mikeoliphant/neural-amp-modeler-lv2"
category = "simulator"

[[plugins]]
name = "GxAmplifier-X"
uri = "http://guitarix.sourceforge.net/plugins/gx_amp#GUITARIX"
category = "simulator"

[[plugins]]
name = "GxCabinet"
uri = "http://guitarix.sourceforge.net/plugins/gx_cabinet#CABINET"
category = "simulator"

[[plugins]]
name = "GxAlembic"
uri = "http://guitarix.sourceforge.net/plugins/gx_studiopre#studiopre"
category = "simulator"

# --- Distortion (server) ---

[[plugins]]
name = "GxFuzz"
uri = "http://guitarix.sourceforge.net/plugins/gx_fuzz_#fuzz_"
category = "distortion"

# --- Delay (server) ---

[[plugins]]
name = "Bollie Delay"
uri = "https://ca9.eu/lv2/bolliedelay"
category = "delay"
# disable_ports = ["in_l"]

[[plugins]]
name = "Gxduck_delay"
uri = "http://guitarix.sourceforge.net/plugins/gx_duck_delay_#_duck_delay_"
category = "delay"

# --- Modulation ---

[[plugins]]
name = "GxFlanger"
uri = "http://guitarix.sourceforge.net/plugins/gx_flanger#_flanger"
category = "modulator"

# --- Pitch / Spectral ---

[[plugins]]
name = "Drop"
uri = "http://moddevices.com/plugins/mod-devel/Drop"
category = "spectral"

[[plugins]]
name = "Gxdetune"
uri = "http://guitarix.sourceforge.net/plugins/gx_detune_#_detune_"
category = "spectral"

[[plugins]]
name = "Pitchotto"
uri = "https://github.com/ninodewit/SHIRO-Plugins/plugins/pitchotto"
category = "spectral"

# --- Dynamics ---

[[plugins]]
name = "Noise Gate"
uri = "http://moddevices.com/plugins/mod-devel/System-NoiseGate"
category = "dynamics"

[[plugins]]
name = "C* Compress"
uri = "http://moddevices.com/plugins/caps/Compress"
category = "dynamics"

# --- Spatial ---

[[plugins]]
name = "C* Wider"
uri = "http://moddevices.com/plugins/caps/Wider"
category = "spatial"

# --- Utility ---

[[plugins]]
name = "Gain 2x2"
uri = "http://moddevices.com/plugins/mod-devel/Gain2x2"
category = "utility"

[[plugins]]
name = "Instrument Tuner"
uri = "http://gareus.org/oss/lv2/tuna#mod"
category = "utility"

[[plugins]]
name = "Record-Mono"
uri = "https://github.com/brummer10/screcord#mono_record"
category = "utility"

[[plugins]]
name = "Record-Stereo"
uri = "https://github.com/brummer10/screcord#stereo_record"
category = "utility"

# --- Generators / Synths ---

[[plugins]]
name = "amsynth"
uri = "http://code.google.com/p/amsynth/amsynth"
category = "generator"


# =============================================================================
# Plugins (from MOD)
# =============================================================================

# --- Distortion / Overdrive (original) ---

[[plugins]]
name = "DS1"
uri = "http://moddevices.com/plugins/mod-devel/DS1"
category = "distortion"

[[plugins]]
name = "KlonCentaur"
uri = "https://github.com/jatinchowdhury18/KlonCentaur"
category = "overdrive"

[[plugins]]
name = "BigMuffPi"
uri = "http://moddevices.com/plugins/mod-devel/BigMuffPi"
category = "distortion"

[[plugins]]
name = "Schrammel OJD"
uri = "https://github.com/JanosGit/Schrammel_OJD"
category = "overdrive"

[[plugins]]
name = "Paranoia"
uri = "http://remaincalm.org/plugins/paranoia"
category = "distortion"

[[plugins]]
name = "GxTubeScreamer"
uri = "http://guitarix.sourceforge.net/plugins/gxts9#ts9sim"
category = "distortion"

# --- Reverb (original) ---

# [[plugins]]
# name = "Calf Reverb"
# uri = "http://calf.sourceforge.net/plugins/Reverb"
# category = "reverb"

# [[plugins]]
# name = "MDA Delay"
# uri = "http://moddevices.com/plugins/mda/Delay"
# category = "delay"

[[plugins]]
name = "MVerb"
uri = "http://distrho.sf.net/plugins/MVerb"
category = "reverb"

[[plugins]]
name = "reverb"
uri = "http://drobilla.net/plugins/fomp/reverb"
category = "reverb"

# [[plugins]]
# name = "Dragonfly Hall Reverb"
# uri = "https://github.com/michaelwillis/dragonfly-reverb"
# category = "reverb"

# --- DELAY ---

[[plugins]]
name = "MDA Delay"
uri = "http://moddevices.com/plugins/mda/Delay"
category = "delay"

# [[plugins]]
# name = "Invada Delay Munge (mono in)"
# uri = "http://invadarecords.com/plugins/lv2/delay/mono"
# category = "delay"

# [[plugins]]
# name = "Invada Delay Munge (sum L+R in)"
# uri = "http://invadarecords.com/plugins/lv2/delay/sum"
# category = "delay"

# --- GENERATOR ---

[[plugins]]
name = "Kars"
uri = "http://distrho.sf.net/plugins/Kars"
category = "generator"

[[plugins]]
name = "C* CEO"
uri = "http://moddevices.com/plugins/caps/CEO"
category = "generator"

[[plugins]]
name = "Nekobi"
uri = "http://distrho.sf.net/plugins/Nekobi"
category = "generator"

[[plugins]]
name = "setBfree DSP Tonewheel Organ"
uri = "http://gareus.org/oss/lv2/b_synth"
category = "generator"

# [[plugins]]
# name = "Black Pearl 4A"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_Black_Pearl_4A"
# category = "generator"

# [[plugins]]
# name = "Black Pearl 4B"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_Black_Pearl_4B"
# category = "generator"

# [[plugins]]
# name = "Black Pearl 5"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_Black_Pearl_5"
# category = "generator"

# [[plugins]]
# name = "Fluid Bass"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidBass"
# category = "generator"

# [[plugins]]
# name = "Fluid Brass"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidBrass"
# category = "generator"

# [[plugins]]
# name = "Fluid Chromatic Percussion"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidChromPerc"
# category = "generator"

# [[plugins]]
# name = "Fluid Drums"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidDrums"
# category = "generator"

# [[plugins]]
# name = "Fluid Ensemble"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidEnsemble"
# category = "generator"

# [[plugins]]
# name = "Fluid Ethnic"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidEthnic"
# category = "generator"

# [[plugins]]
# name = "Fluid Guitars"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidGuitars"
# category = "generator"

# [[plugins]]
# name = "Fluid Organs"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidOrgans"
# category = "generator"

# [[plugins]]
# name = "Fluid Percussion"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidPercussion"
# category = "generator"

# [[plugins]]
# name = "Fluid Pianos"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidPianos"
# category = "generator"

# [[plugins]]
# name = "Fluid Pipes"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidPipes"
# category = "generator"

# [[plugins]]
# name = "Fluid Reeds"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidReeds"
# category = "generator"

# [[plugins]]
# name = "Fluid SoundFX"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidSoundFX"
# category = "generator"

# [[plugins]]
# name = "Fluid Strings"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidStrings"
# category = "generator"

# [[plugins]]
# name = "Fluid SynthFX"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidSynthFX"
# category = "generator"

# [[plugins]]
# name = "Fluid SynthLeads"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidSynthLeads"
# category = "generator"

# [[plugins]]
# name = "Fluid SynthPads"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_FluidSynthPads"
# category = "generator"

# [[plugins]]
# name = "Red Zeppelin 4"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_Red_Zeppelin_4"
# category = "generator"

# [[plugins]]
# name = "Red Zeppelin 5"
# uri = "http://kxstudio.linuxaudio.org/plugins/FluidPlug_Red_Zeppelin_5"
# category = "generator"

# --- SIMULATOR ---

[[plugins]]
name = "AIDA-X"
uri = "http://aidadsp.cc/plugins/aidadsp-bundle/rt-neural-generic"
category = "simulator"

# --- SPATIAL ---

[[plugins]]
name = "Ping Pong Pan"
uri = "http://distrho.sf.net/plugins/PingPongPan"
category = "spatial"

# NOTE: use it to override inputs
# disable_inputs = ["lv2_audio_in_1", "lv2_audio_out_1"]
# join_audio_inputs = true

# --- FILTER ---

[[plugins]]
name = "Auto-wah"
uri = "http://drobilla.net/plugins/fomp/autowah"
category = "filter"

[[plugins]]
name = "x42-eq - Parametric Equalizer Mono"
uri = "http://gareus.org/oss/lv2/fil4#mono"
category = "filter"

[[plugins]]
name = "x42-eq - Parametric Equalizer Stereo"
uri = "http://gareus.org/oss/lv2/fil4#stereo"
category = "filter"

[[plugins]]
name = "GxQuack"
uri = "http://guitarix.sourceforge.net/plugins/gx_quack_#_quack_"
category = "filter"

# --- DYNAMICS ---

# [[plugins]]
# name = "abGate"
# uri = "http://hippie.lt/lv2/gate"
# category = "dynamics"

# [[plugins]]
# name = "Invada Compressor (mono)"
# uri = "http://invadarecords.com/plugins/lv2/compressor/mono"
# category = "dynamics"

# [[plugins]]
# name = "Invada Compressor (stereo)"
# uri = "http://invadarecords.com/plugins/lv2/compressor/stereo"
# category = "dynamics"

# --- MODULATOR ---

[[plugins]]
name = "CS Chorus 1"
uri = "http://drobilla.net/plugins/fomp/cs_chorus1"
category = "modulator"

[[plugins]]
name = "CS Chorus 2"
uri = "http://drobilla.net/plugins/fomp/cs_chorus2"
category = "modulator"

[[plugins]]
name = "CS Phaser 1 with LFO"
uri = "http://drobilla.net/plugins/fomp/cs_phaser1_lfo"
category = "modulator"

[[plugins]]
name = "Triple chorus"
uri = "http://drobilla.net/plugins/fomp/triple_chorus"
category = "modulator"
join_audio_outputs = true

[[plugins]]
name = "setBfree Whirl Speaker"
uri = "http://gareus.org/oss/lv2/b_whirl#mod"
category = "modulator"

# [[plugins]]
# name = "Invada Stereo Phaser (mono in)"
# uri = "http://invadarecords.com/plugins/lv2/phaser/mono"
# category = "modulator"

# [[plugins]]
# name = "Invada Stereo Phaser (stereo in)"
# uri = "http://invadarecords.com/plugins/lv2/phaser/stereo"
# category = "modulator"

# [[plugins]]
# name = "Invada Stereo Phaser (sum L+R in)"
# uri = "http://invadarecords.com/plugins/lv2/phaser/sum"
# category = "modulator"


# --- SPECTRAL ---

[[plugins]]
name = "Autotune"
uri = "http://gareus.org/oss/lv2/fat1"
category = "spectral"

# --- UTILITY ---

# [[plugins]]
# name = "Level Meter"
# uri = "http://gareus.org/oss/lv2/modmeter"
# category = "utility"

# [[plugins]]
# name = "Spectrum Analyzer"
# uri = "http://gareus.org/oss/lv2/modspectre"
# category = "utility"

[[plugins]]
name = "TinyGain Mono"
uri = "http://gareus.org/oss/lv2/tinygain#mono"
category = "utility"

# [[plugins]]
# name = "TinyGain Stereo"
# uri = "http://gareus.org/oss/lv2/tinygain#stereo"
# category = "utility"

[[plugins]]
name = "Stereo X-Fade"
uri = "http://gareus.org/oss/lv2/xfade"
category = "utility"

# [[plugins]]
# name = "Audio File"
# uri = "http://kxstudio.sf.net/carla/plugins/audiofile"
# category = "utility"

# [[plugins]]
# name = "MIDI File"
# uri = "http://kxstudio.sf.net/carla/plugins/midifile"
# category = "utility"

# [[plugins]]
# name = "C* AutoFilter"
# uri = "http://moddevices.com/plugins/caps/AutoFilter"
# category = "filter"

# [[plugins]]
# name = "C* Click - Metronome"
# uri = "http://moddevices.com/plugins/caps/Click"
# category = "utility"


# --- CONTROL VOLTAGE

# [[plugins]]
# name = "AMS Envelope"
# uri = "http://github.com/blablack/ams-lv2/env"
# category = "controlvoltage"

# [[plugins]]
# name = "AMS LFO2 - Freq"
# uri = "http://github.com/blablack/ams-lv2/lfo2_freq"
# category = "controlvoltage"

# [[plugins]]
# name = "AMS VCA Exp"
# uri = "http://github.com/blablack/ams-lv2/vcaexp"
# category = "controlvoltage"

# [[plugins]]
# name = "AMS VCA Lin"
# uri = "http://github.com/blablack/ams-lv2/vcalin"
# category = "controlvoltage"

# [[plugins]]
# name = "AMS VCF"
# uri = "http://github.com/blablack/ams-lv2/vcf"
# category = "controlvoltage"

# [[plugins]]
# name = "AMS VCO3"
# uri = "http://github.com/blablack/ams-lv2/vco3"
# category = "controlvoltage"

# --- MIDI ---

# [[plugins]]
# name = "MIDI Clock Generator"
# uri = "http://gareus.org/oss/lv2/mclk"
# category = "midi"

# [[plugins]]
# name = "MIDI CC to Note"
# uri = "http://gareus.org/oss/lv2/midifilter#cctonote"
# category = "midi"

# [[plugins]]
# name = "MIDI Channel Filter"
# uri = "http://gareus.org/oss/lv2/midifilter#channelfilter"
# category = "midi"

# [[plugins]]
# name = "MIDI Channel Map"
# uri = "http://gareus.org/oss/lv2/midifilter#channelmap"
# category = "midi"

# [[plugins]]
# name = "MIDI Enforce Scale"
# uri = "http://gareus.org/oss/lv2/midifilter#enforcescale"
# category = "midi"

# [[plugins]]
# name = "MIDI Event Filter"
# uri = "http://gareus.org/oss/lv2/midifilter#eventblocker"
# category = "midi"

# [[plugins]]
# name = "MIDI Key-Range Filter"
# uri = "http://gareus.org/oss/lv2/midifilter#keyrange"
# category = "midi"

# [[plugins]]
# name = "MIDI Keysplit"
# uri = "http://gareus.org/oss/lv2/midifilter#keysplit"
# category = "midi"

# [[plugins]]
# name = "MIDI CC Map"
# uri = "http://gareus.org/oss/lv2/midifilter#mapcc"
# category = "midi"

# [[plugins]]
# name = "MIDI Note/Channel Map"
# uri = "http://gareus.org/oss/lv2/midifilter#mapkeychannel"
# category = "midi"

# [[plugins]]
# name = "MIDI Note Transpose"
# uri = "http://gareus.org/oss/lv2/midifilter#mapkeyscale"
# category = "midi"

# [[plugins]]
# name = "MIDI Chord"
# uri = "http://gareus.org/oss/lv2/midifilter#midichord"
# category = "midi"

# [[plugins]]
# name = "MIDI Delayline"
# uri = "http://gareus.org/oss/lv2/midifilter#mididelay"
# category = "midi"

# [[plugins]]
# name = "MIDI Channel Unisono"
# uri = "http://gareus.org/oss/lv2/midifilter#mididup"
# category = "midi"

# [[plugins]]
# name = "MIDI Strum"
# uri = "http://gareus.org/oss/lv2/midifilter#midistrum"
# category = "midi"

# [[plugins]]
# name = "MIDI Chromatic Transpose"
# uri = "http://gareus.org/oss/lv2/midifilter#miditranspose"
# category = "midi"

# [[plugins]]
# name = "MIDI Monophonic Legato"
# uri = "http://gareus.org/oss/lv2/midifilter#monolegato"
# category = "midi"

# [[plugins]]
# name = "MIDI Remove Active Sensing"
# uri = "http://gareus.org/oss/lv2/midifilter#noactivesensing"
# category = "midi"

# [[plugins]]
# name = "MIDI Duplicate Blocker"
# uri = "http://gareus.org/oss/lv2/midifilter#nodup"
# category = "midi"

# [[plugins]]
# name = "MIDI Note to CC"
# uri = "http://gareus.org/oss/lv2/midifilter#notetocc"
# category = "midi"

# [[plugins]]
# name = "MIDI Note Toggle"
# uri = "http://gareus.org/oss/lv2/midifilter#notetoggle"
# category = "midi"

# [[plugins]]
# name = "MIDI N-Tap Delay"
# uri = "http://gareus.org/oss/lv2/midifilter#ntapdelay"
# category = "midi"

# [[plugins]]
# name = "MIDI Simple Channel Filter"
# uri = "http://gareus.org/oss/lv2/midifilter#onechannelfilter"
# category = "midi"

# [[plugins]]
# name = "MIDI Quantization"
# uri = "http://gareus.org/oss/lv2/midifilter#quantize"
# category = "midi"

# [[plugins]]
# name = "MIDI Velocity Randomization"
# uri = "http://gareus.org/oss/lv2/midifilter#randvelocity"
# category = "midi"

# [[plugins]]
# name = "MIDI Scale CC Value"
# uri = "http://gareus.org/oss/lv2/midifilter#scalecc"
# category = "midi"

# [[plugins]]
# name = "MIDI Sostenuto"
# uri = "http://gareus.org/oss/lv2/midifilter#sostenuto"
# category = "midi"

# [[plugins]]
# name = "MIDI Velocity-Range Filter"
# uri = "http://gareus.org/oss/lv2/midifilter#velocityrange"
# category = "midi"

# [[plugins]]
# name = "MIDI Velocity Adjust"
# uri = "http://gareus.org/oss/lv2/midifilter#velocityscale"
# category = "midi"

# [[plugins]]
# name = "MIDI Generator"
# uri = "http://gareus.org/oss/lv2/midigen"
# category = "midi"

# [[plugins]]
# name = "MIDI Step Sequencer16x8"
# uri = "http://gareus.org/oss/lv2/stepseq#s16n8"
# category = "midi"

# [[plugins]]
# name = "MIDI Step Sequencer32x8"
# uri = "http://gareus.org/oss/lv2/stepseq#s32n8"
# category = "midi"

# [[plugins]]
# name = "MIDI Step Sequencer8x16"
# uri = "http://gareus.org/oss/lv2/stepseq#s8n16"
# category = "midi"

# [[plugins]]
# name = "MIDI Step Sequencer8x4"
# uri = "http://gareus.org/oss/lv2/stepseq#s8n4"
# category = "midi"

# [[plugins]]
# name = "MIDI Step Sequencer8x8"
# uri = "http://gareus.org/oss/lv2/stepseq#s8n8"
# category = "midi"

[[plugins]]
name = "The Infamous Mindi"
uri = "http://ssj71.github.io/infamousPlugins/plugs.html#mindi"
category = "midi"
